// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqsbmrjyrgknmsyofeap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxc2Jtcmp5cmdrbm1zeW9mZWFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMTAyMjYsImV4cCI6MjA1OTg4NjIyNn0.b8AufVAWATXd8qcP7pcJNh8A9vnxFiaR2Mcu5PFhhXg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);