name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
      - run: npm i
      - run: npm run dev
      - name: Run server in background
        run: |
          npm run dev &  # run in background
          sleep 5        # give it a few seconds to start
      
      - name: Test server is working
        run: |
          curl -f http://localhost:8080 || (echo "Server not responding!" && exit 1)

